#importonce

/*
I/O stuff
Code: methos
*/

.const sprx0 = $d000
.const spry0 = $d001
.const sprx1 = $d002
.const spry1 = $d003
.const sprx2 = $d004
.const spry2 = $d005
.const sprx3 = $d006
.const spry3 = $d007
.const sprx4 = $d008
.const spry4 = $d009
.const sprx5 = $d00a
.const spry5 = $d00b
.const sprx6 = $d00c
.const spry6 = $d00d
.const sprx7 = $d00e
.const spry7 = $d00f

.const sprxhi = $d010

.const sprmask = $d015

.const sprcol0 = $d027
.const sprcol1 = $d028
.const sprcol2 = $d029
.const sprcol3 = $d02a
.const sprcol4 = $d02b
.const sprcol5 = $d02c
.const sprcol6 = $d02d
.const sprcol7 = $d02e

.const sid = $d400
.const colram = $d800
